name: JXGC Notify
on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发/
    - cron: '0 * * * *' 
   # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天23点59分
    
jobs:
  run-JD-tool:
    runs-on: ubuntu-latest
    steps:
    - name: 企业微信开始推送消息
      run: |
        # 完整的输入企业微信机器人webhook地址,例:https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxx-403c-8cae-23dxxxxxxx021
        curl '${{secrets.QYWX}}' \
        -H 'Content-Type: application/json' \
        -d '
        {
              "msgtype": "text",
              "text": {
                  "content": "京喜工厂领电力"
              }
        }'
