name: JD-daily-task
on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发/
    - cron: '0 16 * * *' 
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（24点整）
    # 建议每个人通过设置 GitHub Environments 的方式来设定为自己的目标运行时间（详细设置方法见文档说明）
jobs:
  run-JD-tool:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: 安装docker
      run: |
        sudo apt-get update && sudo apt-get install -y python3-pip curl vim git moreutils
        pip3 install --upgrade pip
        pip install docker-compose
    - name: 运行脚本
      run: |
        ls
    - name: Create tmate session
      #uses: cyz0105/debugger-action@mai
      run: |
        cp $GITHUB_WORKSPACE/ssh2action.sh ./script.sh
        chmod +x ./script.sh
        ./script.sh 2>&1 | tee ssh.log
    
    - name: SSH connection to Actions
      #uses: cyz0105/debugger-action@mai
      run: |
        echo 'please wait for 5 seconds'
        sleep 5
        echo 'your tmate link is:'
        cat ssh.log | grep https
        echo "请输入在tmate页面按一次Ctrl+C,再输入命令cd openwrt && make menuconfig 运行"
        echo "输入'touch /tmp/finished'以结束ssh开始编译"
        echo "::group::$(cat ssh.log | grep https)"
        for((i=1;i<3601;i+=10)); do if [ ! -f /tmp/finished ];then echo "/////////////////////////////////////////////";cat ssh.log | grep https;echo "/////////////////////////////////////////////";echo "  ";echo "  ";echo "type 'touch /tmp/finished' if you want to continue compile ";echo "  ";echo "  ";else break ;fi; sleep 10; done
    
        
